/* TinyTimer Chaos Edition — 100 distinct features. Source of truth. Icons are vector keys, never emoji. */
window.CHAOS_FEATURES = [
  { id: 1,  cat: "timer",   icon: "pause", name: "Pause & Resume", blurb: "Freeze the countdown mid-tick and thaw it without losing a second.", action: "pauseResume" },
  { id: 2,  cat: "timer",   icon: "forge", name: "Custom Time Forge", blurb: "Type any minutes and seconds; the forge stamps a brand-new duration.", action: "customTimeForge" },
  { id: 3,  cat: "timer",   icon: "tomato", name: "Pomodoro Trinity", blurb: "One-tap 25 / 5 / 15 — work, short break, long break.", action: "pomodoroTrinity" },
  { id: 4,  cat: "timer",   icon: "tea", name: "Tea Ceremony", blurb: "Steep presets for green, black, oolong, and herbal leaf magic.", action: "teaCeremony" },
  { id: 5,  cat: "timer",   icon: "egg", name: "Egg Laboratory", blurb: "Soft, jammy, and hard-boiled egg countdowns from a pocket lab.", action: "eggLab" },
  { id: 6,  cat: "timer",   icon: "stopwatch", name: "Stopwatch Ascent", blurb: "Flip gravity: count up from zero instead of down to doom.", action: "stopwatchAscent" },
  { id: 7,  cat: "timer",   icon: "flame", name: "Tabata Inferno", blurb: "20 seconds on, 10 off, eight rounds of interval fire.", action: "tabataInferno" },
  { id: 8,  cat: "timer",   icon: "swords", name: "Twin Timer Duel", blurb: "Two independent clocks, A and B, racing in parallel universes.", action: "twinTimerDuel" },
  { id: 9,  cat: "timer",   icon: "globe", name: "World Clock Carousel", blurb: "Live hours in Tokyo, NYC, London, Cairo, Sao Paulo, and more.", action: "worldClockCarousel" },
  { id: 10, cat: "timer",   icon: "alarm", name: "Alarm Sundial", blurb: "Set an AM/PM wake time; Chronos yells when the sun hits it.", action: "alarmSundial" },
  { id: 11, cat: "timer",   icon: "calendar", name: "Date Horizon", blurb: "Countdown to a calendar date until the horizon arrives.", action: "dateHorizon" },
  { id: 12, cat: "timer",   icon: "scope", name: "Millisecond Microscope", blurb: "Reveal hundredths of a second under a temporal microscope.", action: "milliMicroscope" },
  { id: 13, cat: "timer",   icon: "flag", name: "Lap Chronicle", blurb: "Stamp split times into a scroll of laps.", action: "lapChronicle" },
  { id: 14, cat: "timer",   icon: "keys", name: "Keyboard Ninja", blurb: "Space start/pause, R reset, L lap, N chaos, arrows for presets.", action: "keyboardNinja" },
  { id: 15, cat: "timer",   icon: "vault", name: "Memory Vault", blurb: "The last duration you forged is remembered across reloads.", action: "memoryVault" },

  { id: 16, cat: "display", icon: "flip", name: "Flip-Clock Splitflap", blurb: "Airport split-flap digits that slap each second into place.", action: "flipClock" },
  { id: 17, cat: "display", icon: "analog", name: "Analog Aura", blurb: "Sweeping hands paint remaining time on a glowing clock face.", action: "analogAura" },
  { id: 18, cat: "display", icon: "binary", name: "Binary Beacon", blurb: "LEDs blink minutes and seconds as pure binary sparks.", action: "binaryBeacon" },
  { id: 19, cat: "display", icon: "morse", name: "Morse Whisper", blurb: "The remaining time is blinked in Morse by a lonely lighthouse.", action: "morseWhisper" },
  { id: 20, cat: "display", icon: "roman", name: "Roman Empire", blurb: "MM:SS rewritten as imperial Roman numerals.", action: "romanEmpire" },
  { id: 21, cat: "display", icon: "sticker", name: "Sticker Numerals", blurb: "Digits become fat vector stickers with soot outlines.", action: "stickerNumerals" },
  { id: 22, cat: "display", icon: "halo", name: "Halo Ring", blurb: "A circular SVG halo drains as your seconds vanish.", action: "haloRing" },
  { id: 23, cat: "display", icon: "hourglass", name: "Hourglass of Ages", blurb: "Sand falls through a glass belly matching remaining time.", action: "hourglassAges" },
  { id: 24, cat: "display", icon: "pixel", name: "Pixel Relic", blurb: "Chunky 8-bit block digits from a lost arcade cabinet.", action: "pixelRelic" },
  { id: 25, cat: "display", icon: "cube", name: "Hypercube", blurb: "A 3D CSS cube tumbles with the time on every face.", action: "hypercube" },
  { id: 26, cat: "display", icon: "scroll", name: "Word Clock Poetry", blurb: "Time spoken as words: FOUR MINUTES REMAIN.", action: "wordClock" },
  { id: 27, cat: "display", icon: "hex", name: "Hex Gate", blurb: "Seconds rendered as hexadecimal runes.", action: "hexGate" },
  { id: 28, cat: "display", icon: "flask", name: "Scientific Notation", blurb: "Remaining time as 3.00 x 10^2 seconds because science.", action: "scientificNotation" },
  { id: 29, cat: "display", icon: "mirror", name: "Mirrorverse", blurb: "Digits reverse into a looking-glass dimension.", action: "mirrorverse" },
  { id: 30, cat: "display", icon: "titan", name: "Colossus Fullscreen", blurb: "The timer swallows the entire viewport like a titan.", action: "colossusFullscreen" },

  { id: 31, cat: "visual",  icon: "confetti", name: "Confetti Cannon", blurb: "A cannon of paper comets when you demand celebration.", action: "confettiCannon" },
  { id: 32, cat: "visual",  icon: "nova", name: "Nova Particle Burst", blurb: "A miniature supernova of sparks from the timer core.", action: "novaBurst" },
  { id: 33, cat: "visual",  icon: "quake", name: "Earthquake Shake", blurb: "The whole stage rattles like a caffeinated tectonic plate.", action: "earthquakeShake" },
  { id: 34, cat: "visual",  icon: "disco", name: "Disco Inferno", blurb: "Strobe hues, spinning highlights, Saturday-night physics.", action: "discoInferno" },
  { id: 35, cat: "visual",  icon: "matrix", name: "Matrix Rain", blurb: "Katakana drizzle behind the clock. Choose a pill optional.", action: "matrixRain" },
  { id: 36, cat: "visual",  icon: "lava", name: "Lava Lamp Blobs", blurb: "Lava blobs drift like bored magma jellyfish.", action: "lavaLamp" },
  { id: 37, cat: "visual",  icon: "wave", name: "Tide Pool Waves", blurb: "Animated tides wash the background in teal melancholy.", action: "tidePool" },
  { id: 38, cat: "visual",  icon: "star", name: "Starfield Warp", blurb: "Stars stretch into hyperspace lines behind the digits.", action: "starfieldWarp" },
  { id: 39, cat: "visual",  icon: "glitch", name: "Glitch Hex", blurb: "RGB split, tear lines, cursed compression artifacts.", action: "glitchHex" },
  { id: 40, cat: "visual",  icon: "crt", name: "CRT Haunting", blurb: "Scanlines, curvature, and a ghost in the shell of 1987.", action: "crtHaunting" },
  { id: 41, cat: "visual",  icon: "firefly", name: "Firefly Garden", blurb: "Bioluminescent bugs orbit the timer like tiny lanterns.", action: "fireflyGarden" },
  { id: 42, cat: "visual",  icon: "star", name: "Lucky Encounter", blurb: "Fate bumps into you. You cannot schedule it.", action: "luckyEncounter" },
  { id: 43, cat: "visual",  icon: "flipg", name: "Gravity Flip", blurb: "UI elements fall upward because physics filed for divorce.", action: "gravityFlip" },
  { id: 44, cat: "visual",  icon: "dvd", name: "DVD Ghost Logo", blurb: "A bouncing logo hunts the perfect corner forever.", action: "dvdGhost" },
  { id: 45, cat: "visual",  icon: "virus", name: "Virus Popup Storm", blurb: "Fake malware windows crash in uninvited. You cannot open them yourself.", action: "virusStorm" },

  { id: 46, cat: "game",    icon: "snake", name: "Neon Snake", blurb: "Eat glowing pellets. Do not become a pretzel.", action: "gameSnake" },
  { id: 47, cat: "game",    icon: "brick", name: "Brick Drop", blurb: "Tetris-lite: stack tetrominoes before the ceiling judges you.", action: "gameBrickDrop" },
  { id: 48, cat: "game",    icon: "flap", name: "Flappy Cube", blurb: "A cube with dreams of birds. Click to flap between pipes.", action: "gameFlappy" },
  { id: 49, cat: "game",    icon: "memory", name: "Memory Constellation", blurb: "Flip star-cards until every constellation finds its twin.", action: "gameMemory" },
  { id: 50, cat: "game",    icon: "mole", name: "Mole Mayhem", blurb: "Whack interdimensional moles before they file taxes.", action: "gameMoles" },
  { id: 51, cat: "game",    icon: "pong", name: "Plasma Pong", blurb: "Classic pong versus a smug AI paddle.", action: "gamePong" },
  { id: 52, cat: "game",    icon: "breakout", name: "Brick Breaker", blurb: "Bounce a comet through a wall of neon bricks.", action: "gameBreakout" },
  { id: 53, cat: "game",    icon: "tictac", name: "Tic-Tac-Nova", blurb: "3x3 warfare against a mildly clever machine.", action: "gameTicTac" },
  { id: 54, cat: "game",    icon: "rps", name: "RPS Colosseum", blurb: "Rock, paper, scissors with crowd roar and score streaks.", action: "gameRPS" },
  { id: 55, cat: "game",    icon: "guess", name: "Oracle Number Guess", blurb: "The oracle picks 1-100. You guess. It is petty.", action: "gameGuess" },
  { id: 56, cat: "game",    icon: "scramble", name: "Word Scramble Storm", blurb: "Unscramble chaotic letter clouds before they drift away.", action: "gameScramble" },
  { id: 57, cat: "game",    icon: "meteor", name: "Typing Meteor", blurb: "Type the falling words or the planet gets a new crater.", action: "gameTyping" },
  { id: 58, cat: "game",    icon: "bolt", name: "Reflex Gauntlet", blurb: "Wait for green, then strike. False starts are shamed.", action: "gameReflex" },
  { id: 59, cat: "game",    icon: "aim", name: "Aim Constellation", blurb: "Click spawning targets; accuracy is a love language.", action: "gameAim" },
  { id: 60, cat: "game",    icon: "cookie", name: "Cookie Nebula Clicker", blurb: "An idle cookie universe. Click. Ascend. Question capitalism.", action: "gameCookie" },
  { id: 61, cat: "game",    icon: "slots", name: "Fortune Slots", blurb: "Three reels of cosmic fruit. Jackpots rain ticks.", action: "gameSlots" },
  { id: 62, cat: "game",    icon: "dice", name: "Dice of Destiny", blurb: "Roll d4/d6/d8/d10/d12/d20 and narrate your fate.", action: "gameDice" },
  { id: 63, cat: "game",    icon: "coin", name: "Coin of Fate", blurb: "A dramatic coin flip with slow-motion spin.", action: "gameCoin" },
  { id: 64, cat: "game",    icon: "merge", name: "Cascade 2048", blurb: "Slide tiles, merge powers of two, chase the mythical 2048.", action: "game2048" },
  { id: 65, cat: "game",    icon: "mine", name: "Minefield Mini", blurb: "8x8 minesweeper with flags and a smug fuse.", action: "gameMines" },
  { id: 66, cat: "game",    icon: "hang", name: "Hangman of Time", blurb: "Guess the secret word or the hourglass grows a stick figure.", action: "gameHangman" },
  { id: 67, cat: "game",    icon: "trivia", name: "Trivia Vortex", blurb: "Original multiple-choice riddles from a chaotic encyclopedia.", action: "gameTrivia" },
  { id: 68, cat: "game",    icon: "simon", name: "Simon Prism", blurb: "Repeat the prism's color song. Memory is a muscle.", action: "gameSimon" },
  { id: 69, cat: "game",    icon: "connect", name: "Gravity Connect Four", blurb: "Drop discs. Connect four. Outwit a greedy AI.", action: "gameConnect4" },
  { id: 70, cat: "game",    icon: "aster", name: "Asteroid Belt", blurb: "Spin, thrust, shoot rocks. Become space dust stylishly.", action: "gameAsteroids" },

  { id: 71, cat: "music",   icon: "synth", name: "Chiptune Synth Lead", blurb: "An 8-bit lead you can jam: square, triangle, saw, noise.", action: "chiptuneLead" },
  { id: 72, cat: "music",   icon: "melody", name: "Alarm Melody Forge", blurb: "Compose a 16-step alarm jingle that fires when time dies.", action: "melodyForge" },
  { id: 73, cat: "music",   icon: "piano", name: "Crystal Piano", blurb: "Two octaves of clickable keys with sustain shimmer.", action: "crystalPiano" },
  { id: 74, cat: "music",   icon: "drum", name: "Thunder Drum Pad", blurb: "Kick, snare, hat, clap, tom, crash — tap the storm.", action: "thunderDrums" },
  { id: 75, cat: "music",   icon: "metro", name: "Metronome Heartbeat", blurb: "BPM slider plus click/wood/cowbell hearts.", action: "metroHeart" },
  { id: 76, cat: "music",   icon: "rain", name: "Soundscape Weather", blurb: "Rain, cafe murmur, forest night, and ocean hush.", action: "soundscapes" },
  { id: 77, cat: "music",   icon: "lofi", name: "Lo-Fi Cloud Generator", blurb: "Procedural dusty drums, vinyl crackle, sleepy chords.", action: "lofiClouds" },
  { id: 78, cat: "music",   icon: "fanfare", name: "Victory Fanfare 8-bit", blurb: "An original 8-bit fanfare that trumpets your tiny wins.", action: "victoryFanfare" },
  { id: 79, cat: "music",   icon: "mic", name: "Song: Tick Tock Forever", blurb: "Original karaoke anthem about clocks that refuse to die.", action: "songTickTock" },
  { id: 80, cat: "music",   icon: "moon", name: "Song: Five More Minutes", blurb: "A sleepy original ballad for every snooze-button poet.", action: "songFiveMore" },
  { id: 81, cat: "music",   icon: "flex", name: "Song: Pomodoro Power", blurb: "Original hype track for tomato-timed glory.", action: "songPomodoro" },
  { id: 82, cat: "music",   icon: "grid", name: "Sequencer Star Grid", blurb: "16x8 note galaxy. Paint a melody. Loop the cosmos.", action: "starGrid" },
  { id: 83, cat: "music",   icon: "theremin", name: "Mouse Theremin", blurb: "Pitch follows X, volume follows Y. Haunt the room.", action: "mouseTheremin" },
  { id: 84, cat: "music",   icon: "uke", name: "Ukulele Strummer", blurb: "C, G, Am, F — island chords with auto-strum.", action: "ukuleleStrum" },
  { id: 85, cat: "music",   icon: "viz", name: "Oscilloscope Visualizer", blurb: "Bars and a waveform that dance to whatever is singing.", action: "oscilloscope" },
  { id: 86, cat: "music",   icon: "loop", name: "Loop Pedal Recorder", blurb: "Capture the last notes you played and loop them.", action: "loopPedal" },
  { id: 87, cat: "music",   icon: "bell", name: "Secret Key Jingles", blurb: "Number keys 1-8 play a hidden scale of tiny bells.", action: "keyJingles" },
  { id: 88, cat: "music",   icon: "mixer", name: "Chaos Volume Mixer", blurb: "Independent faders for SFX, music, ambience, and Chronos.", action: "volumeMixer" },

  { id: 89, cat: "insane",  icon: "cookie", name: "Fortune Cookie Oracle", blurb: "Crack a cookie; receive an aggressively specific prophecy.", action: "fortuneCookie" },
  { id: 90, cat: "insane",  icon: "eight", name: "Magic 8-Sphere", blurb: "Ask the sphere. It answers with cosmic shrug energy.", action: "magic8" },
  { id: 91, cat: "insane",  icon: "dragon", name: "Ember the Timer Dragon", blurb: "A virtual dragon pet: feed, play, watch it snooze on the clock.", action: "emberDragon" },
  { id: 92, cat: "insane",  icon: "badge", name: "Badge Constellation", blurb: "Unlock achievement badges for chaos, music, and high scores.", action: "badgeConstellation" },
  { id: 93, cat: "insane",  icon: "streak", name: "Daily Streak Flame", blurb: "Open TinyTimer on consecutive days; the flame grows vain.", action: "dailyStreak" },
  { id: 94, cat: "insane",  icon: "boss", name: "Boss Fight: Alarmoth", blurb: "When it feels like it, the moth of alarms crashes the party. Not on demand.", action: "bossAlarmoth" },
  { id: 95, cat: "insane",  icon: "konami", name: "Konami Warp Gate", blurb: "Up Up Down Down Left Right Left Right B A opens a secret rainbow song.", action: "konamiGate" },
  { id: 96, cat: "insane",  icon: "shop", name: "Side Street Shop", blurb: "A tiny kiosk on the edge of the stage. Spend ticks. Never the main event.", action: "sideShop" },
  { id: 97, cat: "insane",  icon: "tung", name: "Tung Tung Tung Sahur Call", blurb: "He calls you. You do not call him. Wood-bat rhythm. Answer or decline.", action: "tungCall" },
  { id: 98, cat: "insane",  icon: "brain", name: "Brainrot Ambush", blurb: "Mini-games and meme callers jump you. There is no queue button.", action: "brainrotAmbush" },
  { id: 99, cat: "insane",  icon: "chaos", name: "Chaos Dice", blurb: "Roll to activate a random other feature. No take-backs.", action: "chaosDice" },
  { id: 100,cat: "insane",  icon: "museum", name: "Museum of 100 Wonders", blurb: "A searchable gallery of every feature, with launch buttons.", action: "museumWonders" }
];
